# Generated by Django 4.0.3 on 2022-04-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_label_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='note',
        ),
        migrations.AddField(
            model_name='label',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.label'),
        ),
    ]
