# Generated by Django 4.0.3 on 2022-04-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_label_note_label_is_archived_note_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
