# Generated by Django 4.0.3 on 2022-04-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_note_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['id'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
